"""Add name field to urls and documents tables

Revision ID: 827840b06bc2
Revises: ecea687dcd72
Create Date: 2025-09-25 17:29:51.255436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827840b06bc2'
down_revision: Union[str, None] = 'ecea687dcd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.String(), nullable=True))
    op.add_column('urls', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'name')
    op.drop_column('documents', 'name')
    # ### end Alembic commands ###
