"""Add file handling fields to documents table

Revision ID: 92c850cd3ff9
Revises: 827840b06bc2
Create Date: 2025-09-25 17:56:44.832526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c850cd3ff9'
down_revision: Union[str, None] = '827840b06bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
