"""Add status and last_analysis_at fields to urls and documents

Revision ID: f8c0c8d70998
Revises: 92c850cd3ff9
Create Date: 2025-09-25 19:11:35.256989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c0c8d70998'
down_revision: Union[str, None] = '92c850cd3ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('last_analysis_at', sa.DateTime(), nullable=True))
    op.add_column('urls', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('urls', sa.Column('last_analysis_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'last_analysis_at')
    op.drop_column('urls', 'status')
    op.drop_column('documents', 'last_analysis_at')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
